name: Format check on push
on: push
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - name: Restore dotnet tools
        uses: xt0rted/dotnet-tool-restore@v1.0.1

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@06fadcf678dd69c6e7446b9f2664a25c6094f6a0
        with:
          action: fix
          version: 4
